version: "3"

services:
  frontend:
    build: ./frontend
    container_name: real-world-docker-frontend
    # ports:
    #   - "3000:3000"
    restart: unless-stopped
    command: serve -s build -l 3000

  api:
    build: ./api
    container_name: real-world-docker-api
    command: npm run start
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - HOST=http://realworld.com
      - MONGO_URL=mongodb://api_db:27017/api
    depends_on:
      - api_db

  auth:
    build: ./auth
    container_name: real-world-docker-auth
    command: npm run start
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - HOST=http://realworld.com
      - MONGO_URL=mongodb://auth_db:27017/auth
    depends_on:
      - auth_db

  nginx:
    image: nginx:stable-alpine
    container_name: real-world-docker-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend

  api_db:
    image: mongo:latest
    container_name: real-world-docker-api-db
    volumes:
      - mongodb_api:/data/db

  auth_db:
    image: mongo:latest
    container_name: real-world-docker-auth-db
    volumes:
      - mongodb_auth:/data/db

volumes:
  mongodb_api:
  mongodb_auth:
